"""
Momentum resolution calculator (Billoir-style).

`MomentumResolutionCalculator` is the central orchestrator used by the runner:

- loads detector plane definitions from CSV (`settings["detectionlayers"]`)
- loads the B-field map and creates a `ParabolicExtrapolator`
- loads a ROOT geometry (`settings["gdmlInput"]`) and uses it to insert passive
  material planes along track steps
- propagates state/covariance through planes, applying:
  - measurement updates at measurement planes
  - multiple-scattering noise at passive material planes
- writes per-track summaries to a ROOT `TNtuple` for later comparisons

The main public API used by scripts is:

    `ComputeResolutions(fourvector, charge, originPosition, PVPosition)`

Outputs
-------
The output ROOT file contains a `TNtuple` named `ntuple` with scalar branches
generated by `GetFillingBranches(...)`.

Design note
-----------
This module currently mixes:

- settings/path handling
- detector/geometry plane building
- physics propagation and filtering
- ROOT output writing

`docs/REFACTOR_PLAN.md` proposes a decomposition into smaller classes.
"""

from tracemalloc import start

import ROOT
import numpy as np 
import os 
import math 
import pandas as pd
from   termcolor import colored
from Core.Plane import Plane
from Core.Matrix  import Matrix
from Core.Propagator import Propagator
from Core.Materials import radlen
from Utils.Logger import Logger
from Core.BField import BField
from Core.TrackState import TrackState 
from Core.ParabolicExtrapolator import ParabolicExtrapolator 
from Core.MaterialAndMeasurementLocator import  MaterialAndMeasurementLocator
from Core.MaterialLocator import MaterialLocator
import random
from prettytable import PrettyTable
from ROOT import TFile, TNtuple, TLorentzVector, TVector3
import array 
from Core.Paths import expand_env_var
from Core.RNTupleMaker import RNtupleMaker
from weightmatrix.io.root_output import RootTupleWriter, TupleSchema
_DEFAULT_FILL_ = -100000.

class MomentumResolutionCalculator :   
    def __init__(self, settings :dict, outFileName : str, flyupto:float ):
        """Initialize the calculator tool"""
        self.settings = settings 
        if "path_geom_pickle" in settings:
            from . import Plane as PlaneModule
            PlaneModule._GEOMETRY_FOLDER_ = settings["path_geom_pickle"]
        self.df                = pd.concat((pd.read_csv(expand_env_var(f), comment ="#", skip_blank_lines=True) for f in settings["detectionlayers"]), ignore_index=True)
        self.dfUse             = self.df[ self.df['Use'] ==1]
        self.planes            = []
        self.MyField           = BField( settings["fieldMap"],     settings["fieldShrinkFactor"] , settings["fieldMagFactor"])        
        self.TrajectoryCreator = ParabolicExtrapolator(self.MyField)
        """
        Add custom Planes Here for the tracking, with their material budget and resolution if they are measurement planes.
        The planes are sorted in z and then used for the tracking and resolution estimation.        
        """
        
        for  z, thick,  sigmaX ,sigmaY, angle, geomLayer, hiteff in zip( self.dfUse['Z'],
                                                                         self.dfUse['thickness'],
                                                                         self.dfUse['sigmaX'],
                                                                         self.dfUse['sigmaY'],
                                                                         self.dfUse['angle'] ,
                                                                         self.dfUse['xyshape'].replace(" ",""),
                                                                         self.dfUse['hiteff']) :
            self.planes.append( Plane(
                zval     = float(z),
                thickness= float(thick), dzMat= 0.0,
                sigmaX   = float(sigmaX) if not( pd.isnull( sigmaX)) else None ,
                sigmaY   = float(sigmaY) if not( pd.isnull( sigmaY)) else None ,
                angle    = float(angle)  if not( pd.isnull( sigmaX)) else None ,
                geomLayer= geomLayer,
                hitefficiency = hiteff
        ))
        self.planes = sorted(self.planes)
        for p in self.planes:  
            Logger.info( p)
        ##### Additional Material Locator configurations #####
        ## we have to add new planes given the material locator we have
        self.MatLocator = MaterialLocator(settings["gdmlInput"])            
        self.storingPlanes = []
        if  "storing_planes" in settings.keys (): 
            csv_file = settings["storing_planes"]
            if not( os.path.exists(csv_file )) : raise ValueError("storing planes csv file not existing")
            self.storingPlanes = self.LoadStoringPlanes( csv_file_input= csv_file)

            if flyupto and flyupto >0 : 
                ## TODO : fix logic and patch this better for vertex origin and z-planes
                self.storingPlanes = [ s for s in self.storingPlanes if s.Z > flyupto]    
    
        """
        Ntuple to create will have some input storing info, including storing planes information
        """
        self.InitTupleMaking(outFileName=outFileName) 
        # self.InitRNTuple(outFileName=outFileName)

    # def InitRNTuple(self, outFileName : str):
    #     columns_add = {}
        
    #     columns_add["int"] = ["charge" , "nVelo", "nUT", "nDownT", "nVeloPixel", "nUTPixel", "nDownTPixel"],
    #     columns_add["float"] = [  "p", "pt", "eta", "phi", "totMat", "ovtx_x", "ovtx_y", "ovtx_z"] +
        
    #     columns_add["float"] += [ f"{var}_{plane}" for var in ["x","y","z","tx","ty"] for plane in ["LastMeasurement", "FirstMeasurement", "LastPlane", "SecondPlane"] ]
    #     columns_add["float"] += [
        
    #         "float" : [ "p", "pt", "eta", "phi", "totMat"] + 
    #                   [ f"{var}_{plane}" for var in ["x","y","z","tx","ty"]           for plane in ["LastMeasurement", "FirstMeasurement", "LastPlane", "SecondPlane"] ] +
    #                   [ f"{var}_{plane.GetName()}" for var in ["x","y","z","tx","ty"] for plane in self.storingPlanes ]
                      
    #     }
                            
                            
    #         #, "RFirstMeasur        columns_add["float"] += [ f"bwd_{var}_{plane.GetName()}" for var in ["x","y","z","tx","ty"] for plane in self.storingPlanes]        }
    #     columns_add["float"] += [f"{var}_{plane.GetName()}" for var in ["x","y","z","tx","ty"] for plane in self.storingPlanes]
    #     columns_add["float"] += [f"fwd_{var}_{plane.GetName()}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY", "pres"] for plane in self.storingPlanes]
    #     columns_add["float"] += [f"bwd_{var}_{plane.GetName()}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY", "pres"] for plane in self.storingPlanes]
    #     columns_add["float"] += [f"fwd_{var}_{plane.GetName()}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY", "pres"] for plane in self.storingPlanes]
    #     columns_add["float"] += [f"bwd_{var}_{plane.GetName()}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY","pres"] for plane in self.storingPlanes]
    #     columns_add["float"] += [f"sum_{var}_{plane.GetName()}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY","pres"] for plane in self.storingPlanes]
        
        
    #     self.OutNTuple = RNtupleMaker(f"{outFileName}:ntuple",
    #         columns_add={
    #             "float": ["charge", "p", "pt", "eta", "phi", "totMat", "nVelo", "nUT", "nDownT", "nVeloPixel", "nUTPixel", "nDownTPixel", "RFirstMeasurementToPV"]
    #         }
    #     )
    # def GetFillingBranches( self , plane_name = ""): 
    # if plane_name == "":
    #     branch_list = ["charge" , "p"    , "pt" , "eta"   , "phi",
    #                     "totMat" , "nVelo", "nUT", "nDownT", 
    #                     "nVeloPixel","nUTPixel", "nDownTPixel",
    #                     "RFirstMeasurementToPV"]
    #     return branch_list
    # else : 
    #     branch_list = [f"{info}_{plane_name}" for info in ["x","y","z","tx","ty"]]
    #     branch_list  +=    [f"fwd_{var}_{plane_name}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY", "pres"]]
    #     branch_list  +=    [f"bwd_{var}_{plane_name}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY","pres"]]
    #     branch_list  +=    [f"sum_{var}_{plane_name}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY","pres"]]
    #     return branch_list
    
    def InitTupleMaking(self, outFileName : str ):         
        # baseline branches to fill
        branch_list = self.GetFillingBranches()
        # branch_list = ["charge" , "p"    , "pt" , "eta"   , "phi",
        #                 "totMat" , "nVelo", "nUT", "nDownT", 
        #                   "nFT", "nMP",
        #                 "nVeloPixel","nUTPixel", "nDownTPixel",
        #                 "RFirstMeasurementToPV"]

        branch_list += self.GetFillingBranches( plane_name= "LastMeasurement")      
        branch_list += self.GetFillingBranches( plane_name= "FirstMeasurement")      
        # branch_list += self.GetFillingBranches( plane_name= "LastPlane")      
        # branch_list += self.GetFillingBranches( plane_name= "PVPlane")      
        # branch_list += self.GetFillingBranches( plane_name= "SecondPlane")
        if len(self.storingPlanes) !=  0 : 
            #append additional branches for the 'storing' planes to keep 
            pnames_added = [] 
            for plane in self.storingPlanes:
                if plane.GetName() == "" : raise ValueError("Plane must have a name")
                branch_list += self.GetFillingBranches( plane_name= plane.GetName(), storing_plane = True)
                pnames_added.append(plane.GetName())
            if len(set(pnames_added)) != len(self.storingPlanes): 
                raise ValueError("Each storing planes must have different names! Please Fix the file")
        # Create the output File And Ntuple (via modular writer)
        if outFileName != "" : 
            schema = TupleSchema(branches=tuple(branch_list))
            self.TupleWriter = RootTupleWriter.open(
                out_file=outFileName,
                schema=schema,
                tuple_name="ntuple",
                title="p resolution for settings z",
            )
            # Keep historical attributes for compatibility with existing code paths.
            self.TFileOut = self.TupleWriter.file
            self.TNtupleOut = self.TupleWriter.tuple
        else : 
            raise ValueError("Must initialize the MomentumResolutionCalcolator with a name for the output File to store final information")
    def LoadStoringPlanes(self, csv_file_input): 
        """
        Given an external csv file , create storing planes according to keywords loaded
        """
        df = pd.read_csv(csv_file_input , comment ="#", skip_blank_lines=True)
        storing_planes = [] 
        for  z, name, geomLayer in zip( df['Z'], df['name'], df['type'].replace(" ","")):
            storing_planes.append( Plane(   zval     =float(z), 
                                            thickness=0.0, 
                                            dzMat= 0.0,
                                            sigmaX    = None, 
                                            sigmaY = None ,
                                            angle     = None,
                                            geomLayer= geomLayer,
                                            hitefficiency = 1.0,
                                            name = name  ))
        names =  [ p.GetName() for p in storing_planes]
        if len(set(names)) != len(storing_planes): raise ValueError("Planes for storing must have different names, fix the csv file!")
        return storing_planes
    def GetFillingBranches( self , plane_name = "", storing_plane = False): 
        if plane_name == "":
            branch_list = ["charge" , "p"    , "pt" , "eta"   , "phi",
                           "totMat" , "nVelo", "nUT", "nDownT", "nFT", "nMP",
                           "nVeloPixel","nUTPixel", "nDownTPixel",
                           "RFirstMeasurementToPV"]
            return branch_list
        else : 
            branch_list = [f"{info}_{plane_name}" for info in ["x","y","z","tx","ty"]]
            branch_list  +=    [f"fwd_{var}_{plane_name}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY", "pres"]]
            # branch_list  +=    [f"bwd_{var}_{plane_name}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY","pres"]]
            # branch_list  +=    [f"sum_{var}_{plane_name}" for var in ["sigmaX" , "sigmaY", "sigmaTX", "sigmaTY","pres"]]
            if storing_plane: 
                branch_list += [ f"fwd_integrated_matbudget_{plane_name}" ]
            return branch_list     
    def MakeTableMaterialMeasurements(self, PLANES):
        from prettytable import PrettyTable
        Mat = PrettyTable()
        # if self.doExtraMaterial : 
        Mat.field_names = ["zLocation [mm]","x/X0 [%]", "z-In-Mat Step [mm]", "sigma(x) [pitch size] [mum]", "sigma(y) [mum]" ]
        IDX = 0
        for plane in PLANES:
            if IDX == 0 : 
                ENTRY_Z = plane.Z
                EXIT_Z  = plane.Z + plane.dzMat/2.
            elif IDX == len(PLANES)-1: 
                ENTRY_Z = plane.Z - plane.dzMat/2.
                EXIT_Z  = plane.Z
            else: 
                ENTRY_Z = plane.Z - plane.dzMat/2.
                EXIT_Z  = plane.Z + plane.dzMat/2.      

            if plane.IsMeasurement : 
                Row = [ f"[{ENTRY_Z:.2f}] -> {plane.Z:.2f} -> [{EXIT_Z:.2f}]",
                        f"{plane.Thickness*100.:.2f}",
                        f"{plane.dzMat:.2f}",
                        f"{    1000*plane.sigmaX:.0f}  [{1000*math.sqrt(12)*abs(plane.sigmaX):.0f}]" if plane.sigmaX != None else "-",
                        f"{abs(1000*plane.sigmaY):.0f} [{1000*math.sqrt(12)*abs(plane.sigmaY):.0f}]" if plane.sigmaY != None else "-"]
                Mat.add_row( [colored(r, 'green') for r in  Row ])
            else : 
                Row = [ f"[{ENTRY_Z:.2f}] -> {plane.Z:.2f} -> [{EXIT_Z:.2f}]",
                        f"{plane.Thickness*100.:.2f}",
                        f"{plane.dzMat:.2f}",
                         "None",
                         "None"   ]        
                Mat.add_row( [colored(r, 'red') for r in  Row ])                          
            IDX+=1
        if self.doExtraMaterial :
            if self.MatLocator.skipVelo : Mat.add_row( [ colored("NO Velo  Material GDML", 'green') , "-", "-","-",'-'])
            else :                        Mat.add_row( [ colored("++ Velo  Material GDML", 'red')   , "-", "-","-",'-'])
            if self.MatLocator.skipRICH : Mat.add_row( [ colored("NO RICH1 Material GDML", 'green') , "-", "-","-",'-'])
            else :                        Mat.add_row( [ colored("++ RICH1 Material GDML", 'red')   , "-", "-","-",'-'])
            if self.MatLocator.skipUT   : Mat.add_row( [ colored("NO UT    Material GDML", 'green') , "-", "-","-",'-'])
            else :                        Mat.add_row( [ colored("++ UT    Material GDML", 'red')   , "-", "-","-",'-'])
            if self.MatLocator.skipSciFi: Mat.add_row( [ colored("NO SciFi Material GDML", 'green') , "-", "-","-",'-'])
            else :                        Mat.add_row( [ colored("++ SciFi Material GDML", 'red')   , "-", "-","-",'-'])
            if self.MatLocator.skipWorld: Mat.add_row( [ colored("NO World Material GDML", 'green') , "-", "-","-",'-'])
            else :                        Mat.add_row( [ colored("++ World Material GDML", 'red')   , "-", "-","-",'-'])                    
        else : 
            Mat.add_row(  [ "No additional x/x0 added" , "","",""])
        print(Mat)
        if self.MatLocator.skipVelo: 
            print(colored( "NOTE: if VP skip: VP_RFFoil,VacTank,VP_PipeSections,VP_RFBox included", "red") )
    def CorrectWithAnglesNClustersSciFi(self, myPlane , MeasWeight, dzInMat):
        if myPlane.IsDownStreamTracker() and myPlane.IsDownStreamFibreTracker():
            Tx_At_Plane     = myPlane.associatedState.TX()
            Ty_At_Plane     = myPlane.associatedState.TY()            
            #maybe to be used to compute the full dz path?    
            dxCrossed = abs(Tx_At_Plane) * 1.10 # the actual SciFi dz is 1.10 mm
            nClusters = math.ceil(dxCrossed/0.250)
            MeasWeight = MeasWeight.Scaled(1./(nClusters*nClusters))
            return MeasWeight
        else :
            return MeasWeight    
    def GetScat2( self , qop:float, beta : float, thickness, slopeX :float, slopeY :float , zLoc: float):
        useRossi= abs(zLoc) > 200.    
        if thickness < 0.002: return 0.
        if useRossi : 
            return math.pow( 15.0 * qop/beta,2 )* thickness * math.sqrt( 1. + slopeX**2 + slopeY**2)
        else: 
            thicknessslope = thickness * math.sqrt( 1. + slopeX**2 + slopeY**2)
            return math.pow( 13.6 * qop/beta * math.sqrt(thicknessslope)* (1.+ 0.038* math.log( thicknessslope)),2)
        
    def Tabulate_Planes( self,planes):            
        t = PrettyTable() 
        t.field_names = [   "Name", "GeomLayer", "STATE IN ACC", "z (plane)" , "x,y,z (state)", "isMeasurement",  "thickness", "dzMat",  "sigmaX", "sigmaY", "alpha","isUT", "isVP", "isFT","isMP", "isDownstream", "isPixel"]
        has_FT  = False 
        has_MP  = False 
        for m in planes:    
            row = [ 
                    m.name, 
                    m.geomLayer,
                    m.HasStateInAcceptance(),
                    f"{m.Z:.2f}",                     
                    f"{m.associatedState.X():.2f},{m.associatedState.Y():.2f},{m.associatedState.Z():.2f}", 
                    m.IsMeasurement, 
                    m.Thickness,
                    m.dzMat , 
                    m.sigmaX, 
                    m.sigmaY, 
                    m.angle, 
                    m.IsUT() ,
                    m.IsVelo() , 
                    m.IsDownStreamFibreTracker(), 
                    m.IsDownStreamPixelTracker(), 
                    m.IsDownStreamTracker(), 
                    m.IsPixelMeasurement()
            ]
            if m.IsMeasurement : row = [ colored(r, 'green') for r in row ]
            else :               row = [ colored(r, 'red')   for r in row ]
            t.add_row( row)
            has_FT = m.IsDownStreamFibreTracker() or has_FT
            has_MP = m.IsDownStreamPixelTracker() or has_MP
        Logger.info(f"{t}")
                        
    def ComputeResolutions(self,   
                            fourvector : TLorentzVector , 
                            charge = +1, 
                            originPosition=(0,0,0) ,
                            PVPosition    =(0,0,0) , 
                            flyupto = -999999999.
    ) -> tuple[Matrix, Matrix]:
        unit = fourvector.Vect().Unit()
        tx = unit.X()/unit.Z()
        ty = unit.Y()/unit.Z()       
        track_props = {
            "p" : fourvector.P(),
            "pt": fourvector.Pt(),
            "eta": fourvector.Eta(),
            "phi": fourvector.Phi(),
            "charge" : charge,
            "px" : fourvector.Px(),
            "py" : fourvector.Py(),
            "pz" : fourvector.Pz(),
            "ovtx_x": originPosition[0],
            "ovtx_y": originPosition[1],
            "ovtx_z": originPosition[2],
            "pv_x": PVPosition[0],
            "pv_y": PVPosition[1],
            "pv_z": PVPosition[2],
            "mass": fourvector.Mag(),
            "tx_orig" : tx, 
            "ty_orig" : ty
        }
        pOrigin    = TVector3( track_props["ovtx_x"], track_props["ovtx_y"], track_props["ovtx_z"])
        pvPosition = TVector3( track_props["pv_x"], track_props["pv_y"], track_props["pv_z"])
        momentum = fourvector.Vect()
        unit     = fourvector.Vect().Unit()
        vOrigin  = TVector3( unit.X()/unit.Z(), unit.Y()/unit.Z(), 1.)
        Logger.debug(f"==================================================================")
        Logger.debug(f"Compute Momentum Resolution for p         = {track_props['p']:.2f} MeV")
        Logger.debug(f"Compute Momentum Resolution for originPos = {originPosition} MMDF(path, factory=None, create=True)")
        Logger.debug(f"Compute Momentum Resolution for originVec = {vOrigin}")
        if not( charge == 1. or charge == -1): 
            raise ValueError("Invalid Charge")        
        ##############################
        # Get the PV position , trac slopes at the origin of the track
        ##############################
        PVX , PVY , PVZ   = track_props["pv_x"], track_props["pv_y"], track_props["pv_z"]
        tx = track_props["tx_orig"]
        ty = track_props["ty_orig"]
        
        # Define State at the Origin of the track
        stateOrigin = TrackState( x = pOrigin.X(), y = pOrigin.Y(), z = pOrigin.Z(), tx = tx, ty=ty, qop= charge/momentum.Mag())        
        # Copy the planes to use for the tracking and p-resolution calculation
        usePlanes = [ p for p in self.planes] 
        Logger.debug(f"Number Of Planes (user)= {len(usePlanes)}")        
        # Add the storing Planes where to store output results 
        if len( self.storingPlanes) != 0 :            
            for p in self.storingPlanes :                 
                usePlanes.append(p)
        Logger.debug(f"Number Of Planes (+storing)= {len(usePlanes)}")                
        # Sort in Z the planes to use 
        usePlanes.append( 
            Plane( zval = stateOrigin.Z(), 
                thickness=0.0, dzMat=0.0, sigmaX=None, sigmaY=None, angle=None, geomLayer="any", hitefficiency=1.0, name="OriginPlane"
            )
        )
        Logger.debug(f"Number Of Planes (+originTrack)= {len(usePlanes)}")                
        usePlanes = sorted(usePlanes)
        usePlanes[0].associatedState = stateOrigin # associate the first plane to the state at the origin of the track
        # create the trajectory and extract material crossed in each step from the state Origin         
        states_in_field, curling = self.TrajectoryCreator.CreateStatesAlongTrajectory(
                stateOrigin = usePlanes[0].associatedState,
                zFinal = 13000., 
                step_size = 400., 
                noCharge = False
        )
        if curling : 
            Logger.warning("Trajectory is curling in the magnetic field, skip track")
            return
        
        Logger.debug(f"States in field to add = {len(states_in_field)}")
        nPlanes_in_field = 0 
        for idx in range(len(states_in_field)) :
            if idx == 0 : continue 
            plane_step = Plane( 
                zval = states_in_field[idx].Z(),
                thickness = 0.0, 
                dzMat = 0.0,
                angle = None, 
                sigmaX = None,
                sigmaY = None, 
                geomLayer = 'any',
                hitefficiency = 1.0,
                name = f"PlaneFromTrajectory_at_z_{states_in_field[idx].Z():.1f}"
            )
            usePlanes.append( plane_step )
            nPlanes_in_field +=1
        usePlanes = sorted( usePlanes)
        Logger.debug(f"Number Of Planes (+points in field)= {len(usePlanes)}")                        
        
        if curling :
            Logger.warning("Trajectory is curling in the magnetic field, skip track")
            return
        
        # usePlanes[0] is the origin state ! 
        for idx in range(1, len(usePlanes)):
            startState = usePlanes[idx-1].associatedState 
            stateEnd, tMat = self.TrajectoryCreator.Propagate( trState = startState, 
                                                               zOld = usePlanes[idx-1].Z, 
                                                               zNew = usePlanes[idx].Z,
                                                               noCharge=False)
            usePlanes[idx].associatedState = stateEnd
            startState = stateEnd
        Planes_Material_Crossed = []  
        nTV = 0
        nUP = 0
        usePlanes = sorted(usePlanes)        
        for idx in range(1, len(usePlanes)):
            # current to next state material found 
            startState     = usePlanes[idx-1].associatedState
            endState       = usePlanes[idx].associatedState
            Material_Crossed_In_Step = self.MatLocator.FindMaterialFromPositionToPosition( startState, endState )
            avg_tx = (startState.TX()  + endState.TX()) /2.
            avg_ty = (startState.TY()  + endState.TY()) /2.
            x_ref = startState.X()
            y_ref = startState.Y()
            z_ref = startState.Z()
            for mat in Material_Crossed_In_Step :
                # print( f"Material Found in Step = \n {mat}")
                entry_z = mat[0]
                exit_z  = mat[1]
                z_mid = (exit_z + entry_z)/2.
                dz      = mat[3]
                x0      = mat[2]
                node_id = mat[4]
                measurement = False 
                sigmaX = None
                sigmaY = None
                angle = None
                geomLayer = "any"
                name = "MaterialFromGDML"
                # Logger.info("node_id of material found in step : " + node_id)                
                if ( ("lvMP" in node_id
                        or "lvT" in node_id 
                        or "lvFT" in node_id 
                        or "MP:SiliconTracker" in node_id 
                        or "FT:SiliconTracker" in node_id 
                        or "lvPCB:PCBBox" in node_id 
                        or "lvStationFull:" in node_id 
                        or "lvStationHalf_shape" in node_id ) ) and (z_mid > 6000. and z_mid < 10000.) :
                    # 30,390
                    measurement = False                     
                    x0 = 305288.4 #air x0 in mm
                    node_id = "AIR-REPLACEMENT-MightyTracker"
                    sigmaX = None
                    sigmaY = None
                    angle = None
                    geomLayer = "any"
                    name = "Air-Replace-MightyTracker-Region"
                if ("lvUP" in node_id or "up" in node_id) and ":Silicon" in node_id and (z_mid < 6000. or z_mid > 10000.) :
                    Logger.debug(f"Found a silicon sensor crossed in lvUP → Measurement to create")
                    measurement = True
                    sigmaX = 0.086/math.sqrt(12)
                    sigmaY = 0.086/math.sqrt(12)
                    geomLayer = "UPGDML"
                    angle = 0. # UP detector !
                    name = "UP-Measurement"   
                    nUP +=1
                if ("lvDet" in node_id and "TVSensorSilicon" in node_id) or ( "TV:SensorSilicon" in node_id) :
                    Logger.debug(f"Found a silicon sensor crossed in TV → Measurement to create")
                    measurement = True
                    sigmaX = 0.055/math.sqrt(12)
                    sigmaY = 0.055/math.sqrt(12)
                    angle = 45.0 # TV detector !
                    geomLayer = "VeloGDML"  
                    name = "TV" 
                    nTV +=1
                deltaZ = abs(exit_z - entry_z)
                if deltaZ != dz : 
                    Logger.warning(f"Delta Z computed {deltaZ} different from dz {dz} for material found, check the material locator configuration and the geometry loaded, use dz as default")
                    raise ValueError("Delta Z computed different from dz for material found, check the material locator configuration and the geometry loaded, use dz as default")
                if measurement : 
                    plane = Plane(  
                        zval = z_mid, # place plane in the middle of the material layer
                        thickness= dz/x0, 
                        dzMat = dz,
                        sigmaX = sigmaX, 
                        sigmaY = sigmaY, 
                        angle = angle, 
                        geomLayer = geomLayer, 
                        hitefficiency=1.0, 
                        name = f"{name}_{node_id}"
                    )
                else: 
                    plane = Plane(  
                        zval = z_mid, # place plane in the middle of the material layer
                        thickness= dz/x0, 
                        dzMat = dz,
                        sigmaX = sigmaX, 
                        sigmaY = sigmaY, 
                        angle = angle, 
                        geomLayer = geomLayer, 
                        hitefficiency=1.0, 
                        name = f"PassiveGDML_{node_id}"
                    )
                StateMidLocation = TrackState( x   = x_ref   + avg_tx * ( z_mid - z_ref),
                                               y   = y_ref   + avg_ty + ( z_mid - z_ref),
                                               z   = z_mid , 
                                               tx  = avg_tx,
                                               ty  = avg_ty, 
                                               qop = charge/momentum.Mag() )
                plane.associatedState = StateMidLocation
                Planes_Material_Crossed.append( plane )
        Logger.debug("Adding Material Crossed Planes to the list of planes to consider for the tracking and resolution estimation")
        Logger.debug(f"N Planes Added = {len(Planes_Material_Crossed)}")
        usePlanes += Planes_Material_Crossed
        usePlanes = sorted(usePlanes)    
        Logger.debug(f"Number Of Planes (+material/measurements in steps from GDML)= {len(usePlanes)}")
        # self.Tabulate_Planes(planes= usePlanes)
        # return         
        
        ################################################################################################
        # With all planes at hand, create and associate a track node state to that location and the corresponding covariance matrix transport matrix
        ################################################################################################
        TransportMatrix_FromZ_To_Next = {} 
        state_current = usePlanes[0].associatedState
        for idx in range(1, len(usePlanes)):
            state_current = usePlanes[idx-1].associatedState            
            plane_start = usePlanes[idx-1]
            plane_end   = usePlanes[idx]
            if usePlanes[idx].Z == usePlanes[idx-1].Z :
                Logger.debug(f"Two planes at the same Z found, check your geometry and material definition! Z = {usePlanes[idx].Z} mm")
                Logger.debug(f"Plane 1 : {usePlanes[idx-1]}")
                Logger.debug(f"Plane 2 : {usePlanes[idx]}")
                # raise ValueError("INVALID STUFF, CHECK ME [2]")
            state_end, transport_mat = self.TrajectoryCreator.Propagate( trState = state_current,
                                             zOld =    plane_start.Z,
                                             zNew =    plane_end.Z,
                                             noCharge = False )
            usePlanes[idx].associatedState = state_end
            if state_end.Z() != usePlanes[idx].Z :
                Logger.error(f"State end Z {state_end.Z()} different from plane Z {usePlanes[idx].Z}, check the settings and the material locator configuration, ERROR")
                raise ValueError(f"State end Z different from plane Z, check the settings and the material locator configuration, ERROR")            
            key     = f"{plane_start.Z:.4f}_{plane_end.Z:.4f}"
            key_inv = f"{plane_end.Z:.4f}_{plane_start.Z:.4f}"
            TransportMatrix_FromZ_To_Next[key]     = transport_mat
            TransportMatrix_FromZ_To_Next[key_inv] = transport_mat.Inverse()    
        # self.Tabulate_Planes(planes= usePlanes)
        counter = { 
            "nVeloMeasurements"      : 0, 
            "nVeloMeasurements_Pixel": 0, 
            "nUTMeasurements"        : 0, 
            "nUTMeasurements_Pixel"  : 0, 
            "nDownMeasurements"      : 0, 
            "nDownMeasurements_Pixel": 0,
            "nMP" : 0, 
            "nFT" : 0
        }
        def update_planes_not_in_acceptance(planes):
            PLANES = [] 
            for p in planes:
                if not(p.HasStateInAcceptance()) :
                    # this plane is not becoming the same but with no material to scatter in 
                    # If the state IS NOT in acceptance, avoid to scatter!                                         
                    p_replace = Plane( zval = p.Z,
                               sigmaX = None,
                               sigmaY = None,
                               angle = None,
                               geomLayer = "any",
                               name = p.name + "_NOT_IN_ACCEPTANCE",
                               hitefficiency = 1.0,
                               dzMat = 0.0,
                               thickness = 0.0)
                    p_replace.Thickness = 0 
                    p_replace.dzMat = 0 
                    p_replace.IsMeasurement = False
                    p_replace.associatedState = p.associatedState
                    PLANES.append(p_replace)
                else: 
                    PLANES.append(p)
            return sorted(PLANES) 
        usePlanes = update_planes_not_in_acceptance(usePlanes)       
        
        integrated_scatter_at_storing_planes = {} 
        Forward_Total_Thickness_Considered_With_Slopes = 0         
        Propagate= Propagator()
        qop = float(charge)/momentum.Mag()
        correctSciFiAngles   = ("correctSciFiAngles"       in self.settings.keys() and self.settings["correctSciFiAngles"]       == True)
        massHypo = 105.66 #muon hypotesis
        p        = abs(1./qop)
        energy = math.sqrt( p**2 + massHypo**2)
        beta = energy/p
        # before running through we have every state and plane , need to drop the ones which do not make tracks in acceptance ! E.G not crossing the material even if a layer is there         
        #############################################################
        ## Forward (Backward) Filter , start with No info at all 
        #############################################################        
        WFWD = Matrix( np.zeros( (5,5), "double") )            
        _storing_planes_names_ = [ p.name for p in self.storingPlanes]
        assert( len(set(_storing_planes_names_)) == len(_storing_planes_names_))
        for idx in range(len(usePlanes)-1):
            Tx_Entry     = usePlanes[idx].associatedState.TX()
            Ty_Entry     = usePlanes[idx].associatedState.TY()
            usePlanes[idx].WPredictForward = WFWD
            entry_z = usePlanes[idx].Z
            exit_z  = usePlanes[idx+1].Z
            STEP_LENGHT = exit_z - entry_z
            ####################################################################################
            # IF THIS IS A MEASUREMENT PLANE
            # BEFORE PROPAGATING AND ADDING MS NOISE, WE ADD INFORMATION
            ####################################################################################            
            if usePlanes[idx].name in _storing_planes_names_ : 
                integrated_scatter_at_storing_planes.update( { usePlanes[idx].name : Forward_Total_Thickness_Considered_With_Slopes} )
            
            if usePlanes[idx].IsMeasurement and not(usePlanes[idx].HasStateInAcceptance()):  
                # self.Tabulate_Planes(planes= usePlanes)                
                Logger.warning(f"Plane at z = {usePlanes[idx].Z} is a measurement but state not in acceptance, check the geometry loaded and the trajectory created, skip adding measurement info for this plane")
                """
                This can happen if the geometry loaded and the material locator configuration are such that the trajectory created is not going through the
                'active' part of the measurement plane, 
                for example if the plane is a pixel sensor and 
                the trajectory goes through the gap between two sensors, 
                or if the plane is a strip sensor and the trajectory goes in between two strips.                
                """                
                Logger.info(f"Plane info : {usePlanes[idx]} skipped for noise and measurement!")
                # raise ValueError("Cannot be a Measurement but State not in ACCEPTANCE for the GDML full based parametric tool usage")                        
            if usePlanes[idx].IsMeasurement ==True  and usePlanes[idx].HasStateInAcceptance() ==True:
                #############################################
                # Is Measurement add counters
                #############################################
                counter["nVeloMeasurements"]         += usePlanes[idx].IsVelo() 
                counter["nVeloMeasurements_Pixel"]   += usePlanes[idx].IsVelo() and usePlanes[idx].IsPixelMeasurement()
                counter["nUTMeasurements"]           += usePlanes[idx].IsUT()
                counter["nUTMeasurements_Pixel"]     += usePlanes[idx].IsUT() and usePlanes[idx].IsPixelMeasurement()
                counter["nDownMeasurements"]         += usePlanes[idx].IsDownStreamTracker()
                counter["nDownMeasurements_Pixel"]   += usePlanes[idx].IsDownStreamTracker() and usePlanes[idx].IsPixelMeasurement()                                        
                counter["nFT"]                       += usePlanes[idx].IsDownStreamTracker() and not(usePlanes[idx].IsPixelMeasurement())
                counter["nMP"]                       += usePlanes[idx].IsDownStreamTracker() and usePlanes[idx].IsPixelMeasurement()
                counter["nDownMeasurements_Pixel"]   += usePlanes[idx].IsDownStreamTracker() and usePlanes[idx].IsPixelMeasurement()                                                        
                #############################################
                # Weight Info to add from Measurement
                #############################################
                MeasWeight =  usePlanes[idx].WMeas
                # if correctSciFiAngles : MeasWeight = self.CorrectWithAnglesNClustersSciFi( myPlane= usePlanes[idx], MeasWeight = MeasWeight, dzInMat = usePlanes[idx].dzMat)
                #############################################
                # Eval with HitEfficiency if measurement to add or not, or only scattering
                #############################################
                # planeDropDueToEff = False
                # if usePlanes[idx].hiteff < 1.0 :  
                #     planeDropDueToEff = random.uniform(0., 1.0) > usePlanes[idx].hiteff                
                #     if planeDropDueToEff : 
                #         counter["nVeloMeasurements"]       -= usePlanes[idx].IsVelo() 
                #         counter["nVeloMeasurements_Pixel"] -= usePlanes[idx].IsVelo() and usePlanes[idx].IsPixelMeasurement()
                #         counter["nUTMeasurements"]         -= usePlanes[idx].IsUT()
                #         counter["nUTMeasurements_Pixel"]   -= usePlanes[idx].IsUT() and usePlanes[idx].IsPixelMeasurement()
                #         counter["nDownMeasurements"]       -= usePlanes[idx].IsDownStreamTracker()
                #         counter["nDownMeasurements_Pixel"] -= usePlanes[idx].IsDownStreamTracker() and usePlanes[idx].IsPixelMeasurement()                       
                #         counter["nFT"] -= usePlanes[idx].IsDownStreamTracker() and not(usePlanes[idx].IsPixelMeasurement())
                #         counter["nMP"] -= usePlanes[idx].IsDownStreamTracker() and usePlanes[idx].IsPixelMeasurement()
                        
                ##############################################################
                #  Add the Measurement weight information here!
                ##############################################################
                # if not(planeDropDueToEff):  WFWD = WFWD + MeasWeight        
                WFWD = WFWD + MeasWeight
            ### add and propagate with scattering.... whatcout the entry,exit, dzMat
            usePlanes[idx].WUpdateForward = WFWD #we added measurement, but we don't really need, we can add measurement after scattered half in the material dzStep.
            if usePlanes[idx].dzMat == None : 
                raise ValueError("Must never happen with navigation in full GDML file, Air should be loaded, vacuum as well")
            if idx != len(usePlanes)-1:
                # retrieve transport matrix to next plane z location
                Transport_State_Matrix_To_Next = TransportMatrix_FromZ_To_Next[f"{entry_z:.4f}_{exit_z:.4f}"]
                Tx_Exit = usePlanes[idx+1].associatedState.TX()
                Ty_Exit = usePlanes[idx+1].associatedState.TY()
                Scat2_Entry_To_Exit = self.GetScat2( qop=qop, beta = beta, thickness=usePlanes[idx].Thickness, slopeX = Tx_Entry, slopeY= Ty_Entry , zLoc= usePlanes[idx].Z)
                WFWD = Propagate.Forward(interaction_point_index = idx   , 
                                        planes= usePlanes , 
                                        win   = WFWD ,
                                        tMat  = Transport_State_Matrix_To_Next)                                
                WFWD = Propagate.MultScat(scattering2 = Scat2_Entry_To_Exit,
                                        win = WFWD , 
                                        tx = Tx_Entry,
                                        ty = Ty_Entry, 
                                        dzMat =  usePlanes[idx].dzMat, 
                                        dzStep=STEP_LENGHT)
                Forward_Total_Thickness_Considered_With_Slopes+= usePlanes[idx].Thickness * math.sqrt( 1. + Tx_Entry**2 + Ty_Entry**2 )
                #usePlanes[idx].Thickness/2. * math.sqrt( 1. + Tx_Exit**2  + Ty_Exit**2  ))
                                                                                                                                                            
        #############################################################
        ## BACKWARD Filter , start with No info at all 
        #############################################################      
        WBWD = Matrix( np.zeros( (5,5), "double") )
        for idx in reversed( range(len(usePlanes))):           
            Tx_At_Plane     = usePlanes[idx].associatedState.TX()
            Ty_At_Plane     = usePlanes[idx].associatedState.TY()            
            usePlanes[idx].WPredictBackward = WBWD
            if usePlanes[idx].IsMeasurement     and not(usePlanes[idx].HasStateInAcceptance()):  
                raise ValueError("Cannot be a Measurement but State not in ACCEPTANCE for the GDML full based parametric tool usage")            
            if usePlanes[idx].IsMeasurement ==True  and usePlanes[idx].HasStateInAcceptance() ==True :                                                           
                #############################################
                # Weight Info to add from Measurement
                #############################################
                MeasWeight =  usePlanes[idx].WMeas
                # if correctSciFiAngles : MeasWeight = self.CorrectWithAnglesNClustersSciFi( myPlane= usePlanes[idx], MeasWeight = MeasWeight, dzInMat = usePlanes[idx].dzMat)
                #############################################
                # Eval with HitEfficiency if measurement to add or not, or only scattering
                #############################################
                planeDropDueToEff = False
                if usePlanes[idx].hiteff < 1.0 :  
                    planeDropDueToEff = random.uniform(0., 1.0) > usePlanes[idx].hiteff
                ##############################################################
                #  Add the Measurement weight information here!
                ##############################################################
                if not(planeDropDueToEff):  WBWD = WBWD + MeasWeight
            usePlanes[idx].WUpdateBackward = WBWD
            if usePlanes[idx].dzMat == None  : raise ValueError("Must never happen with navigation in full GDML file, Air should be loaded, vacuum as well")
            if idx >0 :
                zOld = usePlanes[idx].Z
                zNew = usePlanes[idx-1].Z
                STEP_LENGHT = abs(zNew - zOld)
                TMat_Prev_Plane = TransportMatrix_FromZ_To_Next[f"{zOld:.4f}_{zNew:.4f}"]            
                Scat2_Exit_To_Entry  = self.GetScat2( qop=qop, beta = beta, thickness=usePlanes[idx-1].Thickness, slopeX = Tx_Exit,  slopeY= Ty_Exit,zLoc= usePlanes[idx-1].Z )
                tx_next_plane = usePlanes[idx-1].associatedState.TX()
                ty_next_plane = usePlanes[idx-1].associatedState.TY()              
                WBWD = Propagate.Backward(interaction_point_index = idx   , 
                                    planes= usePlanes , 
                                    win   = WBWD ,
                                    tMat  = TMat_Prev_Plane)            
                # Logger.info( f"Backwarding MSCAT {zOld} -> {zNew}")
                WBWD = Propagate.MultScat(scattering2 = Scat2_Exit_To_Entry,
                                        win = WBWD , 
                                        tx = Tx_Entry,
                                        ty = Ty_Entry, dzMat =  usePlanes[idx-1].dzMat, dzStep=STEP_LENGHT, backwardFit=True)              
        #### end of backward 
        totMat           = 100*Forward_Total_Thickness_Considered_With_Slopes
        nVelo            = counter["nVeloMeasurements"]
        nVeloPixel       = counter["nVeloMeasurements_Pixel"]        
        nUT              = counter["nUTMeasurements"]
        nUTPixel         = counter["nUTMeasurements_Pixel"]
        nFT              = counter["nFT"]
        nMP              = counter["nMP"]
        nDownT           = counter["nDownMeasurements"]
        nDownTPixel      = counter["nDownMeasurements_Pixel"]
        Logger.debug(f"""
        Total Thickness Considered with Slopes = {totMat:.2f} % X0
        Number of Velo Measurements = {nVelo} , of which {nVeloPixel} are Pixel
        Number of UT Measurements   = {nUT} , of which {nUTPixel} are Pixel
        Number of Downstream Tracker Measurements = {nDownT} , of which {nDownTPixel} are Pixel, of which {nFT} are FT and {nMP} are MP        
        """)
        """        
        From the full forwarding we have a last z of planes we pass through to use        
        """     
        #Find first measurement and eval the Radial distance of it
        RFirstMeasurementToPV = -99999.
        PVX = sorted(usePlanes)[0].associatedState.X()
        PVY = sorted(usePlanes)[0].associatedState.Y()
        PVZ = sorted(usePlanes)[0].associatedState.Z()     
        planes_info_store = { }

        #already Fill the First and Last measurement as with flyupto != 0 there is no guarantee that the track makes it into the acceptance
        planes_info_store.update( {   "FirstMeasurement"  : self._FILL_DICT_PLANE_(  plane= usePlanes[0] , momentum= momentum.Mag())  }) #assume in the first plane
        planes_info_store.update( {   "LastMeasurement"   : self._FILL_DICT_PLANE_(  plane= usePlanes[-1], momentum= momentum.Mag())  }) #assume in the last plane

        #discover the first measurement on track
        for p in sorted(usePlanes):
            if p.IsMeasurement and p.HasStateInAcceptance():
                RFirstMeasurementToPV = math.sqrt( (p.associatedState.X()-PVX)**2 +   (p.associatedState.Y()-PVY)**2)
                planes_info_store.update( {   "FirstMeasurement"  : self._FILL_DICT_PLANE_(  plane= p , momentum= momentum.Mag())  })
                break
        #discover the last measurement on track 
        for p in reversed( sorted(usePlanes)) :
            if p.IsMeasurement and p.HasStateInAcceptance() : 
                planes_info_store.update( {   "LastMeasurement"   : self._FILL_DICT_PLANE_(  plane= p , momentum= momentum.Mag())  })
                break 
        
        #discover the storing planes to fill
        for p in usePlanes :
            if p.GetName() == "" : continue
            if p.name in _storing_planes_names_: 
                planes_info_store.update( { p.name : self._FILL_DICT_PLANE_(  plane = p           , momentum= momentum.Mag(), integrated_x_over_x0=100* integrated_scatter_at_storing_planes[p.GetName()] ) })
        planes_info_store.update( {    "LastPlane"  : self._FILL_DICT_PLANE_(  plane= usePlanes[-1], momentum= momentum.Mag()) })
        planes_info_store.update( {    "PVPlane"    : self._FILL_DICT_PLANE_(  plane= usePlanes[0] , momentum= momentum.Mag()) })
        planes_info_store.update( {    "SecondPlane": self._FILL_DICT_PLANE_(  plane= usePlanes[1] , momentum= momentum.Mag()) })

        #create a filling array
        #the order matters to what is declared when initializing the tuples branches (InitTupleMaking)
        #and order of filling logic
        filling_array  = [ charge, fourvector.Vect().Mag(), 
                                   fourvector.Vect().Pt(), 
                                   fourvector.Vect().Eta(), 
                                   fourvector.Vect().Phi()]
        filling_array += [ totMat, 
                        nVelo, nUT, nDownT , nFT, nMP, 
                        nVeloPixel, nUTPixel, nDownTPixel,                           
                        RFirstMeasurementToPV ]
        filling_array += [ planes_info_store["LastMeasurement"][key] for key in ["x", "y", "z", "tx", "ty" , 
                                                                                "FWD_sigma_x" , "FWD_sigma_y", "FWD_sigma_tx", "FWD_sigma_ty" , "FWD_sigmap_over_p"]]
                                                                                # "BWD_sigma_x" , "BWD_sigma_y", "BWD_sigma_tx", "BWD_sigma_ty" , "BWD_sigmap_over_p",
                                                                                # "SUM_sigma_x" , "SUM_sigma_y", "SUM_sigma_tx", "SUM_sigma_ty" , "SUM_sigmap_over_p" ] ]
        filling_array += [ planes_info_store["FirstMeasurement"][key] for key in ["x", "y", "z", "tx", "ty" , 
                                                                                "FWD_sigma_x" , "FWD_sigma_y", "FWD_sigma_tx", "FWD_sigma_ty" , "FWD_sigmap_over_p"]]
                                                                                # "BWD_sigma_x" , "BWD_sigma_y", "BWD_sigma_tx", "BWD_sigma_ty" , "BWD_sigmap_over_p",
                                                                                # "SUM_sigma_x" , "SUM_sigma_y", "SUM_sigma_tx", "SUM_sigma_ty" , "SUM_sigmap_over_p" ] ]
        # filling_array += [ planes_info_store["LastPlane"][key] for key in ["x", "y", "z", "tx", "ty" , 
        #                                                                         "FWD_sigma_x" , "FWD_sigma_y", "FWD_sigma_tx", "FWD_sigma_ty" , "FWD_sigmap_over_p",
        #                                                                         "BWD_sigma_x" , "BWD_sigma_y", "BWD_sigma_tx", "BWD_sigma_ty" , "BWD_sigmap_over_p",
        #                                                                         "SUM_sigma_x" , "SUM_sigma_y", "SUM_sigma_tx", "SUM_sigma_ty" , "SUM_sigmap_over_p" ] ]
        # filling_array += [ planes_info_store["PVPlane"][key] for key in ["x", "y", "z", "tx", "ty" , 
        #                                                                         "FWD_sigma_x" , "FWD_sigma_y", "FWD_sigma_tx", "FWD_sigma_ty" , "FWD_sigmap_over_p",
        #                                                                         "BWD_sigma_x" , "BWD_sigma_y", "BWD_sigma_tx", "BWD_sigma_ty" , "BWD_sigmap_over_p",
        #                                                                         "SUM_sigma_x" , "SUM_sigma_y", "SUM_sigma_tx", "SUM_sigma_ty" , "SUM_sigmap_over_p" ] ]
        # filling_array += [ planes_info_store["SecondPlane"][key] for key in ["x", "y", "z", "tx", "ty" , 
        #                                                                         "FWD_sigma_x" , "FWD_sigma_y", "FWD_sigma_tx", "FWD_sigma_ty" , "FWD_sigmap_over_p",
        #                                                                         "BWD_sigma_x" , "BWD_sigma_y", "BWD_sigma_tx", "BWD_sigma_ty" , "BWD_sigmap_over_p",
        #                                                                         "SUM_sigma_x" , "SUM_sigma_y", "SUM_sigma_tx", "SUM_sigma_ty" , "SUM_sigmap_over_p" ] ]
                                                                        
        for plane in self.storingPlanes:
            filling_array += [ 
                planes_info_store[plane.GetName()][key]   for key in ["x", "y", "z", "tx", "ty" , 
                                                                    "FWD_sigma_x" , "FWD_sigma_y", "FWD_sigma_tx", "FWD_sigma_ty" , "FWD_sigmap_over_p",
                                                                    # "BWD_sigma_x" , "BWD_sigma_y", "BWD_sigma_tx", "BWD_sigma_ty" , "BWD_sigmap_over_p", 
                                                                    # "SUM_sigma_x" , "SUM_sigma_y", "SUM_sigma_tx", "SUM_sigma_ty" , "SUM_sigmap_over_p",
                                                                    "integrated_matbudget" ]  #new 
            ]
        fillingArray = array.array('f', filling_array)
        self.TNtupleOut.Fill(fillingArray)
    def _FILL_DICT_PLANE_( self, plane : Plane , momentum : float , integrated_x_over_x0 = None  ): 
        """
        Given a plane , fill the dictionary to fill the branches needed on this plane
        """
        # Logger.debug("FILLDICTPLANE")
        # Logger.info( plane)
        dict_fill = { 
            "x" : plane.associatedState.X(),
            "y" : plane.associatedState.Y(),
            "z" : plane.associatedState.Z(),
            "tx" : plane.associatedState.TX(),
            "ty" : plane.associatedState.TY(),
        }        
        try    : 
            CovPredict = plane.WPredictForward.Inverse()
            dict_fill.update( { 
                "FWD_sigma_ty"         : math.sqrt(          CovPredict.matrix[3][3] ),
                "FWD_sigma_tx"         : math.sqrt(          CovPredict.matrix[2][2] ),
                "FWD_sigma_y"          : math.sqrt(          CovPredict.matrix[1][1] ),
                "FWD_sigma_x"          : math.sqrt(          CovPredict.matrix[0][0] ),
                "FWD_sigmap_over_p"    : momentum*math.sqrt( CovPredict.matrix[4][4] )
            })
        except :
            dict_fill.update( { 
                "FWD_sigma_ty"         : _DEFAULT_FILL_,
                "FWD_sigma_tx"         : _DEFAULT_FILL_,
                "FWD_sigma_y"          : _DEFAULT_FILL_,
                "FWD_sigma_x"          : _DEFAULT_FILL_,
                "FWD_sigmap_over_p"    : _DEFAULT_FILL_
            })
        
        try    : 
            CovPredict = plane.WPredictBackward.Inverse()
            dict_fill.update( { 
                "BWD_sigma_ty"         : math.sqrt(          CovPredict.matrix[3][3] ),
                "BWD_sigma_tx"         : math.sqrt(          CovPredict.matrix[2][2] ),
                "BWD_sigma_y"          : math.sqrt(          CovPredict.matrix[1][1] ),
                "BWD_sigma_x"          : math.sqrt(          CovPredict.matrix[0][0] ),
                "BWD_sigmap_over_p"    : momentum*math.sqrt( CovPredict.matrix[4][4] )
            })                            
        except :
            dict_fill.update( { 
                "BWD_sigma_ty"         : _DEFAULT_FILL_,
                "BWD_sigma_tx"         : _DEFAULT_FILL_,
                "BWD_sigma_y"          : _DEFAULT_FILL_,
                "BWD_sigma_x"          : _DEFAULT_FILL_,
                "BWD_sigmap_over_p"    : _DEFAULT_FILL_
            })

        try    : 
            CovPredict = (plane.WPredictForward + plane.WPredictBackward).Inverse()
            dict_fill.update( { 
                "SUM_sigma_ty"         : math.sqrt(          CovPredict.matrix[3][3] ),
                "SUM_sigma_tx"         : math.sqrt(          CovPredict.matrix[2][2] ),
                "SUM_sigma_y"          : math.sqrt(          CovPredict.matrix[1][1] ),
                "SUM_sigma_x"          : math.sqrt(          CovPredict.matrix[0][0] ),
                "SUM_sigmap_over_p"    : momentum*math.sqrt( CovPredict.matrix[4][4] )
            })                            
        except :
            dict_fill.update( { 
                "SUM_sigma_ty"         : _DEFAULT_FILL_,
                "SUM_sigma_tx"         : _DEFAULT_FILL_,
                "SUM_sigma_y"          : _DEFAULT_FILL_,
                "SUM_sigma_x"          : _DEFAULT_FILL_,
                "SUM_sigmap_over_p"    : _DEFAULT_FILL_
            })
        if integrated_x_over_x0 != None : 
            dict_fill.update( {"integrated_matbudget" : integrated_x_over_x0})
        return dict_fill        
    def SaveTupleToTFile(self):
        """
        Finalize and store information to disk
        """
        # Prefer the modular writer if available.
        if hasattr(self, "TupleWriter") and self.TupleWriter is not None:
            self.TupleWriter.close()
        else:
            self.TFileOut.WriteObjectAny(self.TNtupleOut, self.TNtupleOut.ClassName(), self.TNtupleOut.GetName())
            self.TFileOut.Close()
